language: android
sudo: required

env:
  global:
    - ANDROID_TARGET=android-25
    - ANDROID_ABI=armeabi-v7a

android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.0
    - android-25
    
    #Extras
    - extra-android-m2repository
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-support
    
#    licenses:
#    - 'android-sdk-preview-license-.+'
#    - 'android-sdk-license-.+'
#    - 'google-gdk-license-.+'
    
before_install:
    - chmod +x gradlew
 
script:
    - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
    - emulator -avd test -no-skin -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
    - "./gradlew build connectedCheck --stacktrace"
