language: android
sudo: required

android:
  components:
#    - platform-tools
#    - tools
    - build-tools-25.0.0
    - android-25
    
    #Extras
    - extra-android-m2repository
    - extra-google-google_play_services
    
before_script:
    - chmod +x gradlew
 
script:
    - ./gradlew build connectedCheck
